/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.unicauca.presentation.views;


import co.unicauca.entity.FormatoA;
import co.unicauca.entity.Persona;
import co.unicauca.entity.EnumModalidad;
import co.unicauca.service.SubmissionService;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMTMaterialLighterIJTheme;

import java.awt.BorderLayout;
import java.awt.Color;
import java.io.File;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author Usuario
 */
public class AdjuntarDocumentos extends javax.swing.JPanel {

    private final SubmissionService submissionService = new SubmissionService();

    private Persona persona;
    private FormatoA formatoA;

    private File archivoPDFSeleccionado;
    private File archivoCartaSeleccionada;
    /**
     * Creates new form AdjuntarDocumentos
     */
    public AdjuntarDocumentos(FormatoA formatoA,Persona persona) {
        this.formatoA = formatoA;
        this.persona=persona;
        initComponents();

        initStyles();


        LocalDate hoy = LocalDate.now();
        Date fechaHoy = Date.from(hoy.atStartOfDay(ZoneId.systemDefault()).toInstant());
        dateChooser.setMinSelectableDate(fechaHoy); // ✅ funciona



        // Habilitar carta laboral solo si es práctica laboral
        if (formatoA.getMode() != EnumModalidad.PRACTICA_PROFESIONAL) {
            btCarta.setEnabled(false);
        }
        
        
    }
    
   private void initStyles() {

    // Look and Feel moderno
    FlatMTMaterialLighterIJTheme.setup();

    txtRutaPDF.setForeground(new Color(30, 144, 255)); // azul moderno
    txtRutaCarta.setForeground(new Color(30, 144, 255));

    // Botones redondeados
    btPDF.putClientProperty("JButton.buttonType", "roundRect");
    btCarta.putClientProperty("JButton.buttonType", "roundRect");
    btnGuardar.putClientProperty("JButton.buttonType", "roundRect");

    // Estilo para el calendario: botón
    //dateChooser.getCalendarButton().putClientProperty("JButton.buttonType", "roundRect");

    // Campo de texto del calendario
      // Campo de texto del calendario
    //((JTextField) dateChooser.getDateEditor().getUiComponent())
        //    .setBackground(Color.WHITE);
   // ((JTextField) dateChooser.getDateEditor().getUiComponent())
          //  .setBorder(javax.swing.BorderFactory.createLineBorder(new Color(30, 144, 255)));

    // 🔹 Colores del popup del calendario (JXMonthView)
    UIManager.put("JXMonthView.background", Color.WHITE);               // Fondo
    UIManager.put("JXMonthView.foreground", Color.BLACK);               // Texto normal
    UIManager.put("JXMonthView.selectionBackground", new Color(200, 230, 255)); // Azul muy suave
    UIManager.put("JXMonthView.selectionForeground", Color.BLACK);      // Texto selección
    UIManager.put("JXMonthView.daysOfTheWeekForeground", Color.DARK_GRAY);
    UIManager.put("JXMonthView.unselectableDayForeground", Color.GRAY);
    
    // 🔹 Actualizar la UI para que tome inmediatamente los cambios
    javax.swing.SwingUtilities.updateComponentTreeUI(this);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenido = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btPDF = new javax.swing.JButton();
        txtRutaPDF = new javax.swing.JLabel();
        btCarta = new javax.swing.JButton();
        txtRutaCarta = new javax.swing.JLabel();
        lblClendario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnVolver = new javax.swing.JButton();
        dateChooser = new com.toedter.calendar.JDateChooser();

        Contenido.setBackground(new java.awt.Color(255, 255, 255));
        Contenido.setPreferredSize(new java.awt.Dimension(646, 530));

        btnGuardar.setBackground(new java.awt.Color(51, 51, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });

        btPDF.setBackground(new java.awt.Color(102, 102, 255));
        btPDF.setText("Adjunte un PDF");
        btPDF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btPDFMousePressed(evt);
            }
        });

        txtRutaPDF.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtRutaPDF.setForeground(new java.awt.Color(51, 51, 255));
        txtRutaPDF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRutaPDF.setText("Ruta");
        txtRutaPDF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btCarta.setBackground(new java.awt.Color(102, 102, 255));
        btCarta.setText("Adjunte un PDF");
        btCarta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCarta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCartaMouseClicked(evt);
            }
        });

        txtRutaCarta.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtRutaCarta.setForeground(new java.awt.Color(51, 51, 255));
        txtRutaCarta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRutaCarta.setText("Ruta");
        txtRutaCarta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblClendario.setBackground(new java.awt.Color(0, 0, 0));
        lblClendario.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblClendario.setText("Fecha de publicacion");

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setText("Carta de aprobacion laboral");
        jLabel1.setMaximumSize(new java.awt.Dimension(112, 19));
        jLabel1.setMinimumSize(new java.awt.Dimension(112, 19));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setText("PDF - Formato A");

        btnVolver.setBackground(new java.awt.Color(51, 51, 255));
        btnVolver.setForeground(new java.awt.Color(51, 51, 255));
        btnVolver.setText("Regresar");
        btnVolver.setBorderPainted(false);
        btnVolver.setContentAreaFilled(false);
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });

        dateChooser.setBackground(new java.awt.Color(153, 153, 153));
        dateChooser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dateChooser.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnVolver)
                        .addGap(154, 154, 154)
                        .addComponent(jLabel2))
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(txtRutaPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(txtRutaCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblClendario))))
                .addContainerGap())
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVolver)
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)))
                .addGap(11, 11, 11)
                .addComponent(btPDF)
                .addGap(7, 7, 7)
                .addComponent(txtRutaPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btCarta)
                .addGap(7, 7, 7)
                .addComponent(txtRutaCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblClendario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {
        if (dateChooser.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha.");
            return;
        }

        LocalDate fechaSeleccionada = dateChooser.getDate().toInstant()
                .atZone(ZoneId.systemDefault()).toLocalDate();
        formatoA.setDate(fechaSeleccionada);

        try {
            // 1️⃣ Crear el FormatoA SIN PUBLICAR
            FormatoA formatoCreado = submissionService.createFormatoA(formatoA);

            if (formatoCreado == null || formatoCreado.getId() == null) {
                System.err.println("❌ No se pudo crear el FormatoA: el ID es nulo");
                return;
            }

            // 2️⃣ Subir archivos PRIMERO
            boolean archivosSubidos = true;

            if (archivoPDFSeleccionado != null) {
                String respuestaPDF = submissionService.subirFormatoAPDF(formatoCreado.getId(), archivoPDFSeleccionado);
                if (respuestaPDF == null) {
                    JOptionPane.showMessageDialog(this, "Error al subir el PDF del Formato A.");
                    archivosSubidos = false;
                } else {
                    System.out.println("PDF subido correctamente: " + respuestaPDF);
                }
            }

            if (archivoCartaSeleccionada != null && formatoCreado.getMode() == EnumModalidad.PRACTICA_PROFESIONAL) {
                String respuestaCarta = submissionService.subirCartaLaboral(formatoCreado.getId(), archivoCartaSeleccionada);
                if (respuestaCarta == null) {
                    JOptionPane.showMessageDialog(this, "Error al subir la carta laboral.");
                    archivosSubidos = false;
                } else {
                    System.out.println("Carta laboral subida correctamente: " + respuestaCarta);
                }
            }

            // 3️⃣ PUBLICAR solo si los archivos se subieron correctamente
            if (archivosSubidos) {
                boolean publicado = submissionService.publicarFormatoA(formatoCreado.getId());
                if (publicado) {
                    JOptionPane.showMessageDialog(this, "Formato A registrado y publicado con éxito.");
                } else {
                    JOptionPane.showMessageDialog(this, "Formato A guardado pero hubo error al publicar.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Formato A guardado pero con errores en archivos.");
            }

            showJPanel(new Principal(persona));

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al guardar el Formato A: " + e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarMouseClicked


    private void btPDFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPDFMousePressed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccionar archivo PDF");
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos PDF", "pdf");
        fileChooser.setFileFilter(filtro);

        int resultado = fileChooser.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            archivoPDFSeleccionado = fileChooser.getSelectedFile();
            txtRutaPDF.setText(archivoPDFSeleccionado.getAbsolutePath());
        }
    }//GEN-LAST:event_btPDFMousePressed

    private void btCartaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCartaMouseClicked
        if (formatoA.getMode() != EnumModalidad.PRACTICA_PROFESIONAL) {
            JOptionPane.showMessageDialog(this, "Solo la modalidad 'Práctica Profesional' permite adjuntar carta laboral.");
            return;
        }

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccionar carta laboral (PDF)");
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos PDF", "pdf");
        fileChooser.setFileFilter(filtro);

        int resultado = fileChooser.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            archivoCartaSeleccionada = fileChooser.getSelectedFile();
            txtRutaCarta.setText(archivoCartaSeleccionada.getAbsolutePath());
        }
    }//GEN-LAST:event_btCartaMouseClicked

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        showJPanel(new DatosFormatoA(persona));
    }//GEN-LAST:event_btnVolverMouseClicked

    private void showJPanel(JPanel pl){
        pl.setSize(641,498);
        pl.setLocation(0, 0);

        Contenido.removeAll();
        Contenido.add(pl, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenido;
    private javax.swing.JButton btCarta;
    private javax.swing.JButton btPDF;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVolver;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblClendario;
    private javax.swing.JLabel txtRutaCarta;
    private javax.swing.JLabel txtRutaPDF;
    // End of variables declaration//GEN-END:variables
}
