/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.unicauca.presentation.views;

import co.unicauca.entity.Anteproyecto;
import co.unicauca.entity.FormatoA;
import co.unicauca.entity.Persona;
import co.unicauca.infra.DtoFormatoA;
import co.unicauca.service.EvaluacionService;

import java.util.List;

/**
 *
 * @author User
 */
public class AsignacionEvaluadores extends javax.swing.JPanel {

    Anteproyecto anteproyectoActual;
    private EvaluacionService evaluacionService;
    private Persona personaLogueado;
    /**
     * Creates new form AsingnacionEvaluadores
     */
    public AsignacionEvaluadores(Persona personaLogueado, EvaluacionService evaluacionService) {
        this.personaLogueado = personaLogueado;
        this.evaluacionService = evaluacionService;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenido = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblUTitulo = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        lblEstudiante = new javax.swing.JLabel();
        lblUEstudiante = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        lblEstudiante2 = new javax.swing.JLabel();
        lblUEstudiante2 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        lblDirector = new javax.swing.JLabel();
        lblUDirector = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        lblModalidad = new javax.swing.JLabel();
        lblUModalidad = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        Icon = new javax.swing.JLabel();
        lblEvaluador1 = new javax.swing.JLabel();
        boxEvaluador1 = new javax.swing.JComboBox<>();
        lblCodirector = new javax.swing.JLabel();
        boxEvaluador2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblPDF = new javax.swing.JLabel();
        btAsignar = new javax.swing.JButton();

        Contenido.setBackground(new java.awt.Color(255, 255, 255));
        Contenido.setForeground(new java.awt.Color(255, 255, 255));
        Contenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitulo.setText("Titulo");
        Contenido.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 26, 61, -1));

        lblUTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblUTitulo.setText("Titulo");
        Contenido.add(lblUTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 23, 233, -1));
        Contenido.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 43, 230, -1));

        lblEstudiante.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblEstudiante.setForeground(new java.awt.Color(0, 0, 0));
        lblEstudiante.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEstudiante.setText("Estudiante");
        Contenido.add(lblEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 52, 92, -1));

        lblUEstudiante.setForeground(new java.awt.Color(51, 51, 51));
        lblUEstudiante.setText("Estudiante");
        Contenido.add(lblUEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 52, 233, -1));
        Contenido.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 72, 230, -1));

        lblEstudiante2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblEstudiante2.setForeground(new java.awt.Color(0, 0, 0));
        lblEstudiante2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEstudiante2.setText("Estudiante");
        Contenido.add(lblEstudiante2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 87, 92, -1));

        lblUEstudiante2.setForeground(new java.awt.Color(51, 51, 51));
        lblUEstudiante2.setText("Estudiante");
        Contenido.add(lblUEstudiante2, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 87, 233, -1));
        Contenido.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 107, 230, -1));

        lblDirector.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblDirector.setForeground(new java.awt.Color(0, 0, 0));
        lblDirector.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDirector.setText("Dir.Proyecto");
        Contenido.add(lblDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 117, -1, -1));

        lblUDirector.setForeground(new java.awt.Color(51, 51, 51));
        lblUDirector.setText("Director");
        Contenido.add(lblUDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 117, 233, -1));
        Contenido.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 137, 230, -1));

        lblModalidad.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblModalidad.setForeground(new java.awt.Color(0, 0, 0));
        lblModalidad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblModalidad.setText("Modalidad");
        Contenido.add(lblModalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 146, -1, -1));

        lblUModalidad.setForeground(new java.awt.Color(51, 51, 51));
        lblUModalidad.setText("Modalidad");
        Contenido.add(lblUModalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 146, 233, -1));
        Contenido.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 166, 230, -1));

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/unicauca/presentation/images/LogoPequeño.png"))); // NOI18N
        Contenido.add(Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 194, 80));

        lblEvaluador1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblEvaluador1.setForeground(new java.awt.Color(0, 0, 0));
        lblEvaluador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEvaluador1.setText("Primer Evaluador");
        Contenido.add(lblEvaluador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 16));

        Contenido.add(boxEvaluador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 192, -1));

        lblCodirector.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblCodirector.setForeground(new java.awt.Color(0, 0, 0));
        lblCodirector.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCodirector.setText("Segundo Evaluador");
        Contenido.add(lblCodirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        Contenido.add(boxEvaluador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 192, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EVALUADORES");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Contenido.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 194, 20));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lblPDF.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblPDF.setForeground(new java.awt.Color(102, 102, 255));
        lblPDF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPDF.setText("RUTA PDF");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPDF, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPDF, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        Contenido.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 193, -1, -1));

        btAsignar.setBackground(new java.awt.Color(51, 51, 255));
        btAsignar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btAsignar.setText("ASIGNAR");
        btAsignar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAsignarMouseClicked(evt);
            }
        });
        Contenido.add(btAsignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btAsignarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAsignarMouseClicked
        if (anteproyectoActual == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No hay un anteproyecto seleccionado.",
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Obtener emails seleccionados en los combos
        String email1 = (String) boxEvaluador1.getSelectedItem();
        String email2 = (String) boxEvaluador2.getSelectedItem();

        if (email1 == null || email2 == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Debe seleccionar ambos evaluadores.",
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (email1.equals(email2)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Los dos evaluadores deben ser diferentes.",
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        Long id = anteproyectoActual.getId();

        // 🔥 LLAMAR AL MÉTODO QUE ACABAMOS DE CREAR
        Anteproyecto actualizado =
                evaluacionService.asignarEvaluadores(id, email1, email2);

        if (actualizado != null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Evaluadores asignados correctamente.",
                    "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No se pudo asignar los evaluadores. Verifique el backend.",
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btAsignarMouseClicked
    public void setAnteproyecto(Anteproyecto anteproyecto) {
        if (anteproyecto == null) return;
        this.anteproyectoActual = anteproyecto;

        // 🏷️ Datos generales
        lblUTitulo.setText(anteproyecto.getTitulo() != null ? anteproyecto.getTitulo() : "Sin título");

        // 🔍 Buscar el FormatoA correspondiente según el título
        List<DtoFormatoA> formatos = evaluacionService.listFormatoA();
        DtoFormatoA formatoRelacionado = null;

        if (formatos != null && !formatos.isEmpty()) {
            for (DtoFormatoA formato : formatos) {
                if (formato.getTitle() != null && formato.getTitle().equalsIgnoreCase(anteproyecto.getTitulo())) {
                    formatoRelacionado = formato;
                    break;
                }
            }
        }

        // 🎓 Si se encontró un formato A con ese título, extraer sus datos
        if (formatoRelacionado != null) {
            // Director
            if (formatoRelacionado.getProjectManager().getEmail() != null) {
                Persona director = evaluacionService.findPersonaByEmail(formatoRelacionado.getProjectManager().getEmail());
                lblUDirector.setText(
                        director != null
                                ? director.getName() + " " + director.getLastname()
                                : "Sin director"
                );
            } else {
                lblUDirector.setText("Sin director");
            }
            if (formatoRelacionado != null) {
                // Llenar combo boxes con docentes disponibles
                cargarEvaluadoresDisponibles(formatoRelacionado.getId());

                // ✅ Mostrar modalidad del FormatoA
                if (formatoRelacionado.getMode() != null) {
                    lblUModalidad.setText(formatoRelacionado.getMode());
                } else {
                    lblUModalidad.setText("Sin modalidad");
                }

// ✅ Mostrar PDF del FormatoA
                if (formatoRelacionado.getArchivoPDF() != null && !formatoRelacionado.getArchivoPDF().isEmpty()) {
                    lblPDF.setText(formatoRelacionado.getArchivoPDF());
                } else {
                    lblPDF.setText("Sin archivo");
                }
            }
            // 👩‍🎓 Estudiantes del formato relacionado
            List<Persona> estudiantes = formatoRelacionado.getEstudiantes();



            if (estudiantes != null && !estudiantes.isEmpty()) {
                Persona est1 = estudiantes.get(0);
                lblUEstudiante.setText(est1.getName() + " " + est1.getLastname());

                if (estudiantes.size() > 1) {
                    Persona est2 = estudiantes.get(1);
                    lblUEstudiante2.setText(est2.getName() + " " + est2.getLastname());
                } else {
                    lblUEstudiante2.setText("Sin segundo estudiante");
                }

            } else {
                lblUEstudiante.setText("Sin estudiantes");
                lblUEstudiante2.setText("Sin segundo estudiante");
            }

        } else {
            // ❌ Si no se encontró FormatoA correspondiente
            lblUDirector.setText("Sin director (no se encontró formato A)");
            lblUEstudiante.setText("Sin estudiantes");
            lblUEstudiante2.setText("Sin segundo estudiante");
        }

    }
    private void cargarEvaluadoresDisponibles(Long idFormatoA) {
        if (idFormatoA == null) return;

        // Obtener docentes
        List<Persona> docentesDisponibles = evaluacionService.listarDocentesDisponibles(idFormatoA);

        // Limpiar comboboxes
        boxEvaluador1.removeAllItems();
        boxEvaluador2.removeAllItems();

        // Llenar comboboxes
        if (docentesDisponibles != null && !docentesDisponibles.isEmpty()) {
            for (Persona docente : docentesDisponibles) {
                boxEvaluador1.addItem(docente.getEmail());
                boxEvaluador2.addItem(docente.getEmail());
            }
        }

        // ✅ Dejar ambos combos SIN selección por defecto
        boxEvaluador1.setSelectedIndex(-1);
        boxEvaluador2.setSelectedIndex(-1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenido;
    private javax.swing.JLabel Icon;
    private javax.swing.JComboBox<String> boxEvaluador1;
    private javax.swing.JComboBox<String> boxEvaluador2;
    private javax.swing.JButton btAsignar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblCodirector;
    private javax.swing.JLabel lblDirector;
    private javax.swing.JLabel lblEstudiante;
    private javax.swing.JLabel lblEstudiante2;
    private javax.swing.JLabel lblEvaluador1;
    private javax.swing.JLabel lblModalidad;
    private javax.swing.JLabel lblPDF;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUDirector;
    private javax.swing.JLabel lblUEstudiante;
    private javax.swing.JLabel lblUEstudiante2;
    private javax.swing.JLabel lblUModalidad;
    private javax.swing.JLabel lblUTitulo;
    // End of variables declaration//GEN-END:variables
}
