/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.unicauca.presentation.views;

/**
 *
 * @author User
 */
public class SubirAnteproyecto extends javax.swing.JPanel {

    /**
     * Creates new form SubirFormatoA
     */
    public SubirAnteproyecto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenido = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jSeparatorTitulo = new javax.swing.JSeparator();
        lbModalidad = new javax.swing.JLabel();
        lblDirector = new javax.swing.JLabel();
        lblCodirector = new javax.swing.JLabel();
        lblEstudiante1 = new javax.swing.JLabel();
        lblEstudiante2 = new javax.swing.JLabel();
        lbObjGen = new javax.swing.JLabel();
        lblObjetivosEspecificos = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btCrear = new javax.swing.JButton();
        jSeparatorTitulo1 = new javax.swing.JSeparator();
        jSeparatorTitulo2 = new javax.swing.JSeparator();
        jSeparatorTitulo3 = new javax.swing.JSeparator();
        jSeparatorTitulo4 = new javax.swing.JSeparator();
        jSeparatorTitulo5 = new javax.swing.JSeparator();
        jSeparatorTitulo6 = new javax.swing.JSeparator();
        jSeparatorTitulo7 = new javax.swing.JSeparator();
        lblUTitulo = new javax.swing.JLabel();
        lblUModalidad = new javax.swing.JLabel();
        lblUDirector = new javax.swing.JLabel();
        lblUCodirector = new javax.swing.JLabel();
        lblUEstudiante1 = new javax.swing.JLabel();
        lblUEstudiante2 = new javax.swing.JLabel();
        lblUObjGen = new javax.swing.JLabel();
        lblUObjEspec = new javax.swing.JLabel();

        Contenido.setBackground(new java.awt.Color(255, 255, 255));
        Contenido.setPreferredSize(new java.awt.Dimension(646, 530));

        lblTitulo.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Titulo");
        lblTitulo.setToolTipText("");

        lbModalidad.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lbModalidad.setForeground(new java.awt.Color(0, 0, 0));
        lbModalidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbModalidad.setText("Modalidad");

        lblDirector.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblDirector.setForeground(new java.awt.Color(0, 0, 0));
        lblDirector.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDirector.setText("Director de proyecto");

        lblCodirector.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblCodirector.setForeground(new java.awt.Color(0, 0, 0));
        lblCodirector.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCodirector.setText("Codirector de proyecto");

        lblEstudiante1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblEstudiante1.setForeground(new java.awt.Color(0, 0, 0));
        lblEstudiante1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstudiante1.setText("Estudiante #1");

        lblEstudiante2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblEstudiante2.setForeground(new java.awt.Color(0, 0, 0));
        lblEstudiante2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstudiante2.setText("Estudiante #2");

        lbObjGen.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lbObjGen.setForeground(new java.awt.Color(0, 0, 0));
        lbObjGen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbObjGen.setText("Objetivo General");

        lblObjetivosEspecificos.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblObjetivosEspecificos.setForeground(new java.awt.Color(0, 0, 0));
        lblObjetivosEspecificos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObjetivosEspecificos.setText("Objetivos especificos");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btCrear.setBackground(new java.awt.Color(51, 51, 255));
        btCrear.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btCrear.setForeground(new java.awt.Color(0, 0, 0));
        btCrear.setText("CREAR");
        btCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCrearMouseClicked(evt);
            }
        });

        lblUTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblUTitulo.setText("Titulo");

        lblUModalidad.setForeground(new java.awt.Color(51, 51, 51));
        lblUModalidad.setText("Titulo");

        lblUDirector.setForeground(new java.awt.Color(51, 51, 51));
        lblUDirector.setText("Titulo");

        lblUCodirector.setForeground(new java.awt.Color(51, 51, 51));
        lblUCodirector.setText("Titulo");

        lblUEstudiante1.setForeground(new java.awt.Color(51, 51, 51));
        lblUEstudiante1.setText("Titulo");

        lblUEstudiante2.setForeground(new java.awt.Color(51, 51, 51));
        lblUEstudiante2.setText("Titulo");

        lblUObjGen.setForeground(new java.awt.Color(51, 51, 51));
        lblUObjGen.setText("Titulo");
        lblUObjGen.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblUObjEspec.setForeground(new java.awt.Color(51, 51, 51));
        lblUObjEspec.setText("Titulo");
        lblUObjEspec.setToolTipText("");
        lblUObjEspec.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblUTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jSeparatorTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbModalidad)
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblUModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jSeparatorTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblDirector)
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblUDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jSeparatorTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCodirector)
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblUCodirector, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jSeparatorTitulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblEstudiante1)
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblUEstudiante1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jSeparatorTitulo5, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblEstudiante2)
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblUEstudiante2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jSeparatorTitulo6, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbObjGen, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblUObjGen, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparatorTitulo7, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ContenidoLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(lblObjetivosEspecificos))))
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblUObjEspec, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jSeparatorTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(btCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblTitulo)
                .addGap(11, 11, 11)
                .addComponent(lblUTitulo)
                .addGap(9, 9, 9)
                .addComponent(jSeparatorTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(lbModalidad)
                .addGap(13, 13, 13)
                .addComponent(lblUModalidad)
                .addGap(4, 4, 4)
                .addComponent(jSeparatorTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lblDirector)
                .addGap(13, 13, 13)
                .addComponent(lblUDirector)
                .addGap(4, 4, 4)
                .addComponent(jSeparatorTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lblCodirector, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblUCodirector)
                .addGap(2, 2, 2)
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparatorTitulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblEstudiante1)))
                .addGap(3, 3, 3)
                .addComponent(lblUEstudiante1)
                .addGap(4, 4, 4)
                .addComponent(jSeparatorTitulo5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblEstudiante2)
                .addGap(13, 13, 13)
                .addComponent(lblUEstudiante2)
                .addGap(4, 4, 4)
                .addComponent(jSeparatorTitulo6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbObjGen)
                .addGap(3, 3, 3)
                .addComponent(lblUObjGen, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparatorTitulo7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblObjetivosEspecificos)))
                .addGap(8, 8, 8)
                .addComponent(lblUObjEspec, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jSeparatorTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCrearMouseClicked
      
    }//GEN-LAST:event_btCrearMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenido;
    private javax.swing.JButton btCrear;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparatorTitulo;
    private javax.swing.JSeparator jSeparatorTitulo1;
    private javax.swing.JSeparator jSeparatorTitulo2;
    private javax.swing.JSeparator jSeparatorTitulo3;
    private javax.swing.JSeparator jSeparatorTitulo4;
    private javax.swing.JSeparator jSeparatorTitulo5;
    private javax.swing.JSeparator jSeparatorTitulo6;
    private javax.swing.JSeparator jSeparatorTitulo7;
    private javax.swing.JLabel lbModalidad;
    private javax.swing.JLabel lbObjGen;
    private javax.swing.JLabel lblCodirector;
    private javax.swing.JLabel lblDirector;
    private javax.swing.JLabel lblEstudiante1;
    private javax.swing.JLabel lblEstudiante2;
    private javax.swing.JLabel lblObjetivosEspecificos;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUCodirector;
    private javax.swing.JLabel lblUDirector;
    private javax.swing.JLabel lblUEstudiante1;
    private javax.swing.JLabel lblUEstudiante2;
    private javax.swing.JLabel lblUModalidad;
    private javax.swing.JLabel lblUObjEspec;
    private javax.swing.JLabel lblUObjGen;
    private javax.swing.JLabel lblUTitulo;
    // End of variables declaration//GEN-END:variables
}
