
package co.unicauca.presentation;

import co.unicauca.service.AuthService;
import co.unicauca.entity.Persona;
import com.google.gson.Gson;
import javax.swing.JOptionPane;
import java.awt.Color;


public class GUILogin extends javax.swing.JFrame {
    

private static final String AUTH_URL = "http://localhost:8080/api/auth/login";
    private final AuthService authService;
    private final Gson gson;
    /**
     * Creates new form GUILogin
     */
  
    public GUILogin() {

        this.authService = new AuthService();
        this.gson = new Gson();
        initComponents(); // ✅ AHORA SÍ ESTÁ PRESENTE
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        Unicauca = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        sepEmail = new javax.swing.JSeparator();
        lbContrasenia = new javax.swing.JLabel();
        sepContrasenia = new javax.swing.JSeparator();
        tfContrasenia = new javax.swing.JPasswordField();
        pnlBttLogin = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();
        lblMensaje2 = new javax.swing.JLabel();
        pnlBttRegistrarse = new javax.swing.JPanel();
        lblRegistrarse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        BackGround.setBackground(new java.awt.Color(255, 255, 255));

        Unicauca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/unicauca/presentation/images/unicauca-02.png"))); // NOI18N
        Unicauca.setText("jLabel1");

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/unicauca/presentation/images/Logo.png"))); // NOI18N
        Logo.setText("jLabel1");

        lbTitulo.setFont(new java.awt.Font("Roboto SemiBold", 1, 36)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lbTitulo.setText("INICIAR SESION");

        lbEmail.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lbEmail.setForeground(new java.awt.Color(51, 51, 51));
        lbEmail.setText("Email");

        tfEmail.setBackground(new java.awt.Color(255, 255, 255));
        tfEmail.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        tfEmail.setText("Ingrese su email");
        tfEmail.setBorder(null);
        tfEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfEmailMousePressed(evt);
            }
        });

        sepEmail.setBackground(new java.awt.Color(255, 255, 255));
        sepEmail.setForeground(new java.awt.Color(0, 0, 0));
        sepEmail.setOpaque(true);

        lbContrasenia.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lbContrasenia.setForeground(new java.awt.Color(51, 51, 51));
        lbContrasenia.setText("Contraseña");

        sepContrasenia.setBackground(new java.awt.Color(255, 255, 255));
        sepContrasenia.setForeground(new java.awt.Color(0, 0, 0));
        sepContrasenia.setOpaque(true);

        tfContrasenia.setBackground(new java.awt.Color(255, 255, 255));
        tfContrasenia.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        tfContrasenia.setForeground(new java.awt.Color(153, 153, 153));
        tfContrasenia.setText("**********");
        tfContrasenia.setBorder(null);
        tfContrasenia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfContraseniaMousePressed(evt);
            }
        });

        pnlBttLogin.setBackground(new java.awt.Color(0, 102, 204));
        pnlBttLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlBttLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBttLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBttLoginMouseExited(evt);
            }
        });

        lblLogin.setBackground(new java.awt.Color(0, 0, 0));
        lblLogin.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setText("ENTRAR");
        lblLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLoginMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pnlBttLoginLayout = new javax.swing.GroupLayout(pnlBttLogin);
        pnlBttLogin.setLayout(pnlBttLoginLayout);
        pnlBttLoginLayout.setHorizontalGroup(
            pnlBttLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBttLoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlBttLoginLayout.setVerticalGroup(
            pnlBttLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBttLoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblMensaje.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(255, 102, 102));
        lblMensaje.setText(" ");

        lblMensaje2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblMensaje2.setForeground(new java.awt.Color(0, 102, 204));
        lblMensaje2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensaje2.setText("¿No tienes usuario?");

        pnlBttRegistrarse.setBackground(new java.awt.Color(0, 102, 204));
        pnlBttRegistrarse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblRegistrarse.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        lblRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistrarse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistrarse.setText("REGISTRARSE");
        lblRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegistrarseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegistrarseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlBttRegistrarseLayout = new javax.swing.GroupLayout(pnlBttRegistrarse);
        pnlBttRegistrarse.setLayout(pnlBttRegistrarseLayout);
        pnlBttRegistrarseLayout.setHorizontalGroup(
            pnlBttRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
        );
        pnlBttRegistrarseLayout.setVerticalGroup(
            pnlBttRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BackGroundLayout = new javax.swing.GroupLayout(BackGround);
        BackGround.setLayout(BackGroundLayout);
        BackGroundLayout.setHorizontalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(lbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(sepEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(lbContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(tfContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackGroundLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BackGroundLayout.createSequentialGroup()
                                .addGap(280, 280, 280)
                                .addComponent(lblMensaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sepContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(pnlBttLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addComponent(pnlBttRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(Unicauca, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BackGroundLayout.setVerticalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sepEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lbContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(tfContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblMensaje2))
                    .addComponent(sepContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBttLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlBttRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(Unicauca)
        );

        pnlBttRegistrarse.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfEmailMousePressed
      if( tfEmail.getText().equals("Ingrese su email")){
       tfEmail.setText("");
       tfEmail.setForeground(Color.BLACK);
      }
      if(String.valueOf(tfContrasenia.getPassword()).isEmpty()){
       tfContrasenia.setText("**********");
       tfContrasenia.setForeground(Color.GRAY);
      }
    }//GEN-LAST:event_tfEmailMousePressed

    private void tfContraseniaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfContraseniaMousePressed
        if(String.valueOf(tfContrasenia.getPassword()).equals("**********")){
        tfContrasenia.setText("");
        tfContrasenia.setForeground(Color.BLACK);
        }
        if(tfEmail.getText().isEmpty()){
        tfEmail.setText("Ingrese su email");
        tfEmail.setForeground(Color.GRAY);}
    }//GEN-LAST:event_tfContraseniaMousePressed

    private void pnlBttLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBttLoginMouseExited
        pnlBttLogin.setBackground(new Color(0,102,204));
    }//GEN-LAST:event_pnlBttLoginMouseExited

    private void pnlBttLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBttLoginMouseEntered
        pnlBttLogin.setBackground(new Color(0,64,128));
    }//GEN-LAST:event_pnlBttLoginMouseEntered



    private void lblLoginMouseClicked(java.awt.event.MouseEvent evt) {
        String email = tfEmail.getText().trim();
        String password = String.valueOf(tfContrasenia.getPassword()).trim();

        // ✅ SOLO validar campos vacíos en el frontend
        if (email.isEmpty() || password.isEmpty() ||
                email.equals("Ingrese su email") || password.equals("**********")) {
            JOptionPane.showMessageDialog(this,
                    "Por favor ingresa email y contraseña",
                    "Campos incompletos",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // ✅ MICROSERVICIO maneja TODA la lógica de validación
            Persona personaLogueada = authService.login(email, password);

            // ✅ Si llegamos aquí, el microservicio aprobó las credenciales
            JOptionPane.showMessageDialog(this,
                    "¡Bienvenido, " + personaLogueada.getName() + "!",
                    "Inicio de sesión exitoso",
                    JOptionPane.INFORMATION_MESSAGE);

            // ✅ CORREGIDO: Pasar Persona del paquete entity
            GUIMenuPrincipal guiPrincipal = new GUIMenuPrincipal(personaLogueada);
            guiPrincipal.setVisible(true);
            this.dispose();

        } catch (Exception e) {
            // ✅ MOSTRAR MENSAJE DE ERROR DEL MICROSERVICIO
            JOptionPane.showMessageDialog(this,
                    e.getMessage(),  // Mensaje del microservicio
                    "Error de autenticación",
                    JOptionPane.ERROR_MESSAGE);
        }
    }






    private void lblLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseEntered
        pnlBttLogin.setBackground(new Color(0,64,128));
    }//GEN-LAST:event_lblLoginMouseEntered

    private void lblRegistrarseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarseMouseEntered
          pnlBttRegistrarse.setBackground(new Color(0,64,128));
    }//GEN-LAST:event_lblRegistrarseMouseEntered

    private void lblRegistrarseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarseMouseExited
        pnlBttRegistrarse.setBackground(new Color(0,102,204));
    }//GEN-LAST:event_lblRegistrarseMouseExited

    private void lblRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarseMouseClicked
        //GUISingIn ventanaSingIn = new GUISingIn(); // crear la nueva ventana
        //ventanaSingIn.setVisible(true);            // mostrarla
        this.dispose();       
    }//GEN-LAST:event_lblRegistrarseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUILogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Unicauca;
    private javax.swing.JLabel lbContrasenia;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblMensaje2;
    private javax.swing.JLabel lblRegistrarse;
    private javax.swing.JPanel pnlBttLogin;
    private javax.swing.JPanel pnlBttRegistrarse;
    private javax.swing.JSeparator sepContrasenia;
    private javax.swing.JSeparator sepEmail;
    private javax.swing.JPasswordField tfContrasenia;
    private javax.swing.JTextField tfEmail;
    // End of variables declaration//GEN-END:variables
}

