/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.unicauca.presentation;

import co.unicauca.entity.Persona;

/**
 *
 * @author User
 */
public class GUIMenuJefe extends javax.swing.JFrame {

    private Persona personaLogueado;
    /**
     * Creates new form GUIMenuJefe
     */
    public GUIMenuJefe(Persona personaLogueado) {
        this.personaLogueado = personaLogueado;
        initComponents();
    }
    public GUIMenuJefe() {}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bakground = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        Icon = new javax.swing.JLabel();
        Titulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btAnteproyectos = new javax.swing.JButton();
        btnCloseSesion = new javax.swing.JButton();
        btRegresar = new javax.swing.JButton();
        Contenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bakground.setBackground(new java.awt.Color(26, 55, 171));
        Bakground.setPreferredSize(new java.awt.Dimension(919, 510));

        Menu.setBackground(new java.awt.Color(26, 55, 171));
        Menu.setPreferredSize(new java.awt.Dimension(270, 512));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/unicauca/presentation/images/LogoPequeño.png"))); // NOI18N
        Icon.setText("jLabel2");
        Menu.add(Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 22, 158, -1));

        Titulo.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Roboto ExtraBold", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(26, 55, 171));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("JEFE DE DEPARTAMENTO");

        javax.swing.GroupLayout TituloLayout = new javax.swing.GroupLayout(Titulo);
        Titulo.setLayout(TituloLayout);
        TituloLayout.setHorizontalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TituloLayout.setVerticalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TituloLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Menu.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 270, -1));

        btAnteproyectos.setBackground(new java.awt.Color(65, 55, 171));
        btAnteproyectos.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        btAnteproyectos.setForeground(new java.awt.Color(255, 255, 255));
        btAnteproyectos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/unicauca/presentation/images/file-chart.png"))); // NOI18N
        btAnteproyectos.setText("Anteproyectos");
        btAnteproyectos.setToolTipText("");
        btAnteproyectos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btAnteproyectos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btAnteproyectos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAnteproyectos.setIconTextGap(7);
        btAnteproyectos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAnteproyectosMouseClicked(evt);
            }
        });
        Menu.add(btAnteproyectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 270, 64));

        btnCloseSesion.setBackground(new java.awt.Color(65, 55, 171));
        btnCloseSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCloseSesion.setText("Cerrar Sesión");
        btnCloseSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseSesionActionPerformed(evt);
            }
        });
        Menu.add(btnCloseSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 457, -1, -1));

        btRegresar.setBackground(new java.awt.Color(65, 55, 171));
        btRegresar.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        btRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/unicauca/presentation/images/file-chart.png"))); // NOI18N
        btRegresar.setText("Volver");
        btRegresar.setToolTipText("");
        btRegresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btRegresar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btRegresar.setIconTextGap(7);
        btRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRegresarMouseClicked(evt);
            }
        });
        Menu.add(btRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 254, 270, 64));

        Contenido.setBackground(new java.awt.Color(255, 255, 255));
        Contenido.setPreferredSize(new java.awt.Dimension(641, 498));

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BakgroundLayout = new javax.swing.GroupLayout(Bakground);
        Bakground.setLayout(BakgroundLayout);
        BakgroundLayout.setHorizontalGroup(
            BakgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BakgroundLayout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );
        BakgroundLayout.setVerticalGroup(
            BakgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
            .addGroup(BakgroundLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bakground, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bakground, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAnteproyectosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAnteproyectosMouseClicked
        GUIAsingarEvaluadores ventanaEval = new GUIAsingarEvaluadores(personaLogueado);
        ventanaEval.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btAnteproyectosMouseClicked

    private void btnCloseSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseSesionActionPerformed
        GUILogin login = new GUILogin();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseSesionActionPerformed

    private void btRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegresarMouseClicked

        GUIMenuPrincipal ventanaPrincipal = new GUIMenuPrincipal(personaLogueado);
        ventanaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btRegresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMenuJefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMenuJefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMenuJefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMenuJefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMenuJefe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bakground;
    private javax.swing.JPanel Contenido;
    private javax.swing.JLabel Icon;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Titulo;
    private javax.swing.JButton btAnteproyectos;
    private javax.swing.JButton btRegresar;
    private javax.swing.JButton btnCloseSesion;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
