/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.unicauca.presentation;



import java.awt.BorderLayout;
import java.util.List;

import co.unicauca.entity.*;
import co.unicauca.presentation.views.ListaFormatosAestudiantes;
import javax.swing.JPanel;
import co.unicauca.presentation.views.ListarAnteproyectos;
import co.unicauca.presentation.views.ListarProyectos;
import co.unicauca.service.EstudianteService;

/**
 *
 * @author User
 */
public class GUIMenuProyecto extends javax.swing.JFrame {

    private Persona personaLogueado;
    private EstudianteService estudianteService;

    public GUIMenuProyecto(Persona logueado) {
        this.personaLogueado = logueado;
        this.estudianteService = new EstudianteService();
        initComponents();
        setLocationRelativeTo(null);
    }

    private void showJPanel(JPanel pl) {
        pl.setSize(641, 498);
        pl.setLocation(0, 0);

        Contenido.removeAll();
        Contenido.setLayout(new BorderLayout());
        Contenido.add(pl, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        Titulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btConsultarFormatoA = new javax.swing.JButton();
        JButtonCloseSesion = new javax.swing.JButton();
        btConsultarAnteproyecto = new javax.swing.JButton();
        btProyecto = new javax.swing.JButton();
        btRegresar = new javax.swing.JButton();
        Contenido = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(26, 55, 171));

        Menu.setBackground(new java.awt.Color(26, 55, 171));
        Menu.setPreferredSize(new java.awt.Dimension(270, 510));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/unicauca/presentation/images/LogoPequeño.png"))); // NOI18N
        lblLogo.setText("jLabel2");

        Titulo.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Roboto ExtraBold", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(26, 55, 171));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PROYECTOS");

        javax.swing.GroupLayout TituloLayout = new javax.swing.GroupLayout(Titulo);
        Titulo.setLayout(TituloLayout);
        TituloLayout.setHorizontalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );
        TituloLayout.setVerticalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        btConsultarFormatoA.setBackground(new java.awt.Color(65, 55, 171));
        btConsultarFormatoA.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        btConsultarFormatoA.setForeground(new java.awt.Color(255, 255, 255));
        btConsultarFormatoA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/unicauca/presentation/images/file-chart.png"))); // NOI18N
        btConsultarFormatoA.setText("FormatoA");
        btConsultarFormatoA.setToolTipText("");
        btConsultarFormatoA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btConsultarFormatoA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btConsultarFormatoA.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btConsultarFormatoA.setIconTextGap(7);
        btConsultarFormatoA.setVerifyInputWhenFocusTarget(false);
        btConsultarFormatoA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btConsultarFormatoAMouseClicked(evt);
            }
        });
        btConsultarFormatoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarFormatoAActionPerformed(evt);
            }
        });

        JButtonCloseSesion.setBackground(new java.awt.Color(65, 55, 171));
        JButtonCloseSesion.setForeground(new java.awt.Color(255, 255, 255));
        JButtonCloseSesion.setText("Cerrar Sesión");
        JButtonCloseSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonCloseSesionActionPerformed(evt);
            }
        });

        btConsultarAnteproyecto.setBackground(new java.awt.Color(65, 55, 171));
        btConsultarAnteproyecto.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        btConsultarAnteproyecto.setForeground(new java.awt.Color(255, 255, 255));
        btConsultarAnteproyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/unicauca/presentation/images/file-chart.png"))); // NOI18N
        btConsultarAnteproyecto.setText("Anteproyecto");
        btConsultarAnteproyecto.setToolTipText("");
        btConsultarAnteproyecto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btConsultarAnteproyecto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btConsultarAnteproyecto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btConsultarAnteproyecto.setIconTextGap(7);
        btConsultarAnteproyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btConsultarAnteproyectoMouseClicked(evt);
            }
        });
        btConsultarAnteproyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarAnteproyectoActionPerformed(evt);
            }
        });

        btProyecto.setBackground(new java.awt.Color(65, 55, 171));
        btProyecto.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        btProyecto.setForeground(new java.awt.Color(255, 255, 255));
        btProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/unicauca/presentation/images/file-chart.png"))); // NOI18N
        btProyecto.setText("Proyecto");
        btProyecto.setToolTipText("");
        btProyecto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btProyecto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btProyecto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btProyecto.setIconTextGap(7);
        btProyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btProyectoMouseClicked(evt);
            }
        });

        btRegresar.setBackground(new java.awt.Color(65, 55, 171));
        btRegresar.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        btRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/unicauca/presentation/images/file-chart.png"))); // NOI18N
        btRegresar.setText("Volver");
        btRegresar.setToolTipText("");
        btRegresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btRegresar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btRegresar.setIconTextGap(7);
        btRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRegresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultarFormatoA, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultarAnteproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(JButtonCloseSesion))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblLogo)
                .addGap(32, 32, 32)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(btRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btConsultarFormatoA, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btConsultarAnteproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(JButtonCloseSesion))
        );

        Contenido.setBackground(new java.awt.Color(255, 255, 255));
        Contenido.setPreferredSize(new java.awt.Dimension(641, 498));

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Contenido, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegresarMouseClicked
        GUIMenuEstudiante menuEstudiante = new GUIMenuEstudiante(personaLogueado);
        menuEstudiante.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btRegresarMouseClicked

    private void btConsultarFormatoAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btConsultarFormatoAMouseClicked

    }//GEN-LAST:event_btConsultarFormatoAMouseClicked

    private void JButtonCloseSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonCloseSesionActionPerformed
        GUILogin login = new GUILogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JButtonCloseSesionActionPerformed

    private void btConsultarFormatoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarFormatoAActionPerformed
        try {
            // 1. Obtener el proyecto del estudiante
            ProyectoGrado proyecto = estudianteService.findProyectoByEstudiante(personaLogueado.getEmail());

            if (proyecto != null) {
                System.out.println("📦 Proyecto encontrado - ID: " + proyecto.getId() +
                        " | FormatoA ID: " + proyecto.getIdFormatoA() + // ✅ USAR idFormatoA
                        " | FormatoA Actual: " + (proyecto.getFormatoAActual() != null ?
                        proyecto.getFormatoAActual().getId() : "null"));

                // 2. Obtener FormatoAVersion actual
                FormatoAVersion formatoActual = estudianteService.findFormatoAVersionByProyectoId(proyecto.getId());

                if (formatoActual != null) {
                    System.out.println("✅ FormatoAVersion encontrado - ID: " + formatoActual.getId() +
                            " | Versión: " + formatoActual.getNumeroVersion());

                    // 3. Obtener todas las versiones usando idFormatoA
                    if (proyecto.getIdFormatoA() != null) {
                        List<FormatoAVersion> versiones = estudianteService.listFormatosAVersion(proyecto.getIdFormatoA());

                        if (versiones != null && !versiones.isEmpty()) {
                            System.out.println("📚 Versiones encontradas: " + versiones.size());
                            ListaFormatosAestudiantes listaFormatosA = new ListaFormatosAestudiantes(versiones);
                            showJPanel(listaFormatosA);
                        } else {
                            System.out.println("⚠️ No se encontraron versiones para FormatoA ID: " + proyecto.getIdFormatoA());
                            // Mostrar solo la versión actual
                            List<FormatoAVersion> versionUnica = List.of(formatoActual);
                            ListaFormatosAestudiantes listaFormatosA = new ListaFormatosAestudiantes(versionUnica);
                            showJPanel(listaFormatosA);
                        }
                    } else {
                        System.out.println("⚠️ El proyecto no tiene FormatoA asociado");
                    }
                } else {
                    System.out.println("⚠️ No se encontró FormatoAVersion para el proyecto");
                }
            } else {
                System.out.println("⚠️ No se encontró proyecto para el estudiante");
            }
        } catch (Exception e) {
            System.err.println("❌ Error al consultar FormatoA: " + e.getMessage());
            e.printStackTrace();
        }

      
    }//GEN-LAST:event_btConsultarFormatoAActionPerformed

    private void btConsultarAnteproyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btConsultarAnteproyectoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btConsultarAnteproyectoMouseClicked

    private void btConsultarAnteproyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarAnteproyectoActionPerformed
        try {
            // 1. Obtener el proyecto del estudiante
            ProyectoGrado proyecto = estudianteService.findProyectoByEstudiante(personaLogueado.getEmail());

            if (proyecto != null) {
                System.out.println("🔍 Buscando anteproyecto para proyecto ID: " + proyecto.getId());

                // 2. ✅ CORREGIDO: Buscar anteproyecto por ID del proyecto
                Anteproyecto anteproyecto = estudianteService.findAnteproyectoByProyectoId(proyecto.getId());

                if (anteproyecto != null) {
                    System.out.println("✅ Anteproyecto encontrado - ID: " + anteproyecto.getId());

                    // 3. Mostrar el anteproyecto (necesitarás crear una vista para esto)
                    ListarAnteproyectos listaAnteproyectos = new ListarAnteproyectos(anteproyecto);
                    showJPanel(listaAnteproyectos);
                } else {
                    System.out.println("⚠️ No se encontró anteproyecto para el proyecto ID: " + proyecto.getId());
                    // Mostrar mensaje al usuario
                }
            } else {
                System.out.println("⚠️ No se encontró proyecto para el estudiante");
            }
        } catch (Exception e) {
            System.err.println("❌ Error al consultar anteproyecto: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btConsultarAnteproyectoActionPerformed

    private void btProyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProyectoMouseClicked
        try {
            // ✅ Obtener el proyecto del estudiante
            ProyectoGrado proyecto = estudianteService.findProyectoByEstudiante(personaLogueado.getEmail());

            if (proyecto != null) {
                // ✅ Mostrar la información del proyecto
                ListarProyectos listaProyectos = new ListarProyectos(proyecto);
                showJPanel(listaProyectos);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btProyectoMouseClicked
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
          /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMenuJefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMenuJefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMenuJefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMenuJefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMenuJefe().setVisible(true);
            }
        });
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Contenido;
    private javax.swing.JButton JButtonCloseSesion;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Titulo;
    private javax.swing.JButton btConsultarAnteproyecto;
    private javax.swing.JButton btConsultarFormatoA;
    private javax.swing.JButton btProyecto;
    private javax.swing.JButton btRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables
}
